### ISSUE TITLE
problem with running deomo

### ISSUE THREAD

**Issue by jakeyahn** [tzt101/MichiGAN#15]
Traceback (most recent call last):
  File "demo.py", line 521, in <module>
    opt = DemoOptions().parse()
  File "/home/student/michigan_test/MichiGAN/options/base_options.py", line 235, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/home/student/anaconda3/envs/michigan_env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

I tried cuda_launch_blocking=1 but still doesnt work..

**Comment by SparshDrolia22** [comment]
In baseoptions line 235 try changing the line to 
torch.cuda.set_device(int('0'))
