### ISSUE TITLE
Cannot load pretrained models

### ISSUE THREAD

**Issue by shionhonda** [tzt101/MichiGAN#8]
Thanks for publishing a great work!

I tried `inference.py` following the procedure described in README, but I got an error at unpickling.

```
Network [SPADEBGenerator] was created. Total number of parameters: 109.5 million. To see the architecture, do print(network).
Network [InpaintGenerator] was created. Total number of parameters: 16.1 million. To see the architecture, do print(network).
Traceback (most recent call last):
  File "inference.py", line 25, in <module>
    model = Pix2PixModel(opt)
  File "/content/MichiGAN/models/pix2pix_model.py", line 32, in __init__
    self.netG, self.netD, self.netE, self.netIG, self.netFE, self.netB, self.netD2, self.netSIG = self.initialize_networks(opt)
  File "/content/MichiGAN/models/pix2pix_model.py", line 185, in initialize_networks
    netG = util.load_network(netG, 'G', opt.which_epoch, opt)
  File "/content/MichiGAN/util/util.py", line 228, in load_network
    weights = torch.load(save_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

So I manually downloaded the .pth files from Google Drive, but again, I got another error at the same point.

```Network [SPADEBGenerator] was created. Total number of parameters: 109.5 million. To see the architecture, do print(network).
Network [InpaintGenerator] was created. Total number of parameters: 16.1 million. To see the architecture, do print(network).
Traceback (most recent call last):
  File "inference.py", line 25, in <module>
    model = Pix2PixModel(opt)
  File "/content/MichiGAN/models/pix2pix_model.py", line 32, in __init__
    self.netG, self.netD, self.netE, self.netIG, self.netFE, self.netB, self.netD2, self.netSIG = self.initialize_networks(opt)
  File "/content/MichiGAN/models/pix2pix_model.py", line 185, in initialize_networks
    netG = util.load_network(netG, 'G', opt.which_epoch, opt)
  File "/content/MichiGAN/util/util.py", line 228, in load_network
    weights = torch.load(save_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 4248659 more bytes. The file might be corrupted.
```

How do I load the pretrained models?

## Versions
- Colaboratory
- Python 3.6.9
- PyTorch 1.7.0
- Cuda 10.1

**Comment by shionhonda** [comment]
The first error was simply that the .pth file was broken. Are you sure that the .sh files are correct?

```
$ cat checkpoints/MichiGAN/50_net_G.pth
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://mailustceducn-my.sharepoint.com/personal/tzt_mail_ustc_edu_cn/......">here</a>.</h2>
</body></html>
```

The second error was my fault. I tried re-uploading the model file to Colaboratory, and it worked!

**Comment by samaypashine** [comment]
How were you able to load the model?? When I went to the link the file "5_net_G.pth" provided, it asked me to sign in with Microsoft account and didn't do anything. What should I do now??
